"use client";
import {NavIcon} from "../../UiBits";
import {SlidingToggleGroup} from "../ui/Primitives";
export type Destination="leaderboard"|"matches"|"availability"|"players"|"settings";
const destinations:{id:Destination;label:string}[]=[{id:"leaderboard",label:"排行榜"},{id:"matches",label:"比賽"},{id:"availability",label:"約戰"},{id:"players",label:"球員"},{id:"settings",label:"設定"}];
/** `describe` carries the badge's meaning, not just its count — a nav badge on this tab can mean
    "N invites are waiting on you" one refresh and "N games are open to join" the next (see
    `navBadgeLabel` in HomeClient), and those are different claims a screen reader must not blur into
    one generic "items pending". Callers that only ever mean one thing can omit it. */
function Badge({count,describe}:{count:number;describe?:string}){return count>0?<><b className="nav-badge" aria-hidden="true">{count>9?"9+":count}</b><span className="ds-sr-only">，{describe??`${count} 項待處理`}</span></>:null}
export function DesktopNavigation({active,onNavigate,badge,badgeLabel,signedIn,needsOnboarding=false}:{active:Destination;onNavigate:(id:Destination)=>void;badge:(id:Destination)=>number;badgeLabel?:(id:Destination)=>string|undefined;signedIn:boolean;needsOnboarding?:boolean}){return <aside className="side ds-desktop-nav"><div className="brand"><span>S</span><div><b>SCAA</b><small>Snooker ELO</small></div>{needsOnboarding&&<a className="onboarding-alert-link" href="/onboarding?reminder=1" aria-label="完成會員問卷" title="完成會員問卷">⚠️</a>}</div><nav aria-label="主導覽">{destinations.map(item=><button key={item.id} className={active===item.id?"active":""} aria-current={active===item.id?"page":undefined} onClick={()=>onNavigate(item.id)}><i><NavIcon id={item.id} active={active===item.id}/><Badge count={badge(item.id)} describe={badgeLabel?.(item.id)}/></i>{item.label}</button>)}</nav><div className="public-note"><b>{signedIn?"會員模式":"公開瀏覽"}</b><span>{signedIn?"已登入，可更新球會資料":"登入會員後即可記錄比賽"}</span>{!signedIn&&<a className="public-note-cta" href="/login?mode=signup">建立帳戶 →</a>}</div></aside>}
export function MobileBottomNav({active,onNavigate,onRecord,recordOpen,badge,badgeLabel}:{active:Destination;onNavigate:(id:Destination)=>void;onRecord:()=>void;recordOpen:boolean;badge:(id:Destination)=>number;badgeLabel?:(id:Destination)=>string|undefined}){const items:[Destination|"record",string][]=[["leaderboard","排行榜"],["matches","比賽"],["record","記錄"],["availability","約戰"],["players","球員"]];const hasVisibleSelection=items.some(([id])=>id===active);return <SlidingToggleGroup as="nav" className={`bottom ds-mobile-nav${hasVisibleSelection?"":" no-selection"}`} aria-label="主導覽">{items.map(([id,label])=>{const count=id==="record"?0:badge(id);return <button key={id} className={`${id==="record"?"bottom-record":active===id?"active":""}${id==="record"&&recordOpen?" menu-open":""}`} aria-current={active===id?"page":undefined} aria-expanded={id==="record"?recordOpen:undefined} aria-haspopup={id==="record"?"menu":undefined} onClick={()=>id==="record"?onRecord():onNavigate(id)}><i>{id==="record"?"＋":<NavIcon id={id} active={active===id}/>}<Badge count={count} describe={id==="record"?undefined:badgeLabel?.(id)}/></i><small>{label}</small></button>})}</SlidingToggleGroup>}
