"use client";
import {NavIcon} from "../../UiBits";
import {SlidingToggleGroup} from "../ui/Primitives";
import {BrandLogo} from "../BrandLogo";
import {useT} from "../I18nProvider";
import type {MessageKey} from "../../../lib/i18n/translate";
export type Destination="leaderboard"|"matches"|"availability"|"players"|"settings";
const destinations:{id:Destination;label:MessageKey}[]=[{id:"leaderboard",label:"nav.leaderboard"},{id:"matches",label:"nav.matches"},{id:"availability",label:"nav.availability"},{id:"players",label:"nav.players"},{id:"settings",label:"nav.settings"}];
/** `describe` carries the badge's meaning, not just its count — a nav badge on this tab can mean
    "N invites are waiting on you" one refresh and "N games are open to join" the next (see
    `navBadgeLabel` in HomeClient), and those are different claims a screen reader must not blur into
    one generic "items pending". Callers that only ever mean one thing can omit it. */
function Badge({count,describe}:{count:number;describe?:string}){
  const t = useT();return count>0?<><b className="nav-badge" aria-hidden="true">{count>9?"9+":count}</b><span className="ds-sr-only">{t("，")}{describe??t("{count} 項待處理", {count})}</span></>:null}
export function DesktopNavigation({active,onNavigate,badge,badgeLabel,signedIn,needsOnboarding=false}:{active:Destination|null;onNavigate:(id:Destination)=>void;badge:(id:Destination)=>number;badgeLabel?:(id:Destination)=>string|undefined;signedIn:boolean;needsOnboarding?:boolean}){const t=useT();return <aside className="side ds-desktop-nav"><div className="brand"><BrandLogo/>{needsOnboarding&&<a className="onboarding-alert-link" href="/onboarding?reminder=1" aria-label={t("完成會員問卷")} title={t("完成會員問卷")}>⚠️</a>}</div><nav aria-label={t("nav.main")}>{destinations.map(item=><button key={item.id} className={active===item.id?"active":""} aria-current={active===item.id?"page":undefined} onClick={()=>onNavigate(item.id)}><i><NavIcon id={item.id} active={active===item.id}/><Badge count={badge(item.id)} describe={badgeLabel?.(item.id)}/></i>{t(item.label)}</button>)}</nav><div className="public-note"><b>{signedIn?t("會員模式"):t("公開瀏覽")}</b><span>{signedIn?t("已登入，可更新球會資料"):t("登入會員後即可記錄比賽")}</span>{!signedIn&&<a className="public-note-cta" href="/login?mode=signup">{t("建立帳戶 →")}</a>}</div></aside>}
export function MobileBottomNav({active,onNavigate,onRecord,recordOpen,badge,badgeLabel}:{active:Destination|null;onNavigate:(id:Destination)=>void;onRecord:()=>void;recordOpen:boolean;badge:(id:Destination)=>number;badgeLabel?:(id:Destination)=>string|undefined}){const t=useT();const items:[Destination|"record",string][]=[["leaderboard",t("nav.leaderboard")],["matches",t("nav.matches")],["record",t("nav.record")],["availability",t("nav.availability")],["players",t("nav.players")]];const hasVisibleSelection=items.some(([id])=>id===active);return <SlidingToggleGroup as="nav" className={`bottom ds-mobile-nav${hasVisibleSelection?"":" no-selection"}`} aria-label={t("nav.main")}>{items.map(([id,label])=>{const count=id==="record"?0:badge(id);return <button key={id} className={`${id==="record"?"bottom-record":active===id?"active":""}${id==="record"&&recordOpen?" menu-open":""}`} aria-current={active===id?"page":undefined} aria-expanded={id==="record"?recordOpen:undefined} aria-haspopup={id==="record"?"menu":undefined} onClick={()=>id==="record"?onRecord():onNavigate(id)}><i>{id==="record"?<svg aria-hidden="true" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12 5v14M5 12h14"/></svg>:<NavIcon id={id} active={active===id}/>}<Badge count={count} describe={id==="record"?undefined:badgeLabel?.(id)}/></i><small>{label}</small></button>})}</SlidingToggleGroup>}
