"use client";
import {useEffect,useMemo,useState} from "react";
import {PlayerBadge} from "./UiBits";
import {trackAvailabilityEvent} from "../lib/availability-analytics";
import {clipToDay,intersectIntervals,mergeIntervals,overlapMinutes,recommendationScore,type AvailabilitySlot,type Interval} from "../lib/availability";
type Player={id:string;name:string;short:string;rating:number;colour?:string;avatar?:string|null};type Match={a:string;b:string;playedOn:string;status:"confirmed"|"void"};type Member=Player&{slots:AvailabilitySlot[]};type Rec={member:Member;overlaps:Interval[];minutes:number;recent:number;score:number;difference:number};type View="find"|"recommendations"|"manage"|"create";
const hkDate=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Hong_Kong",year:"numeric",month:"2-digit",day:"2-digit"}).format(d),time=(iso:string)=>new Intl.DateTimeFormat("zh-HK",{timeZone:"Asia/Hong_Kong",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso)),range=(x:Interval)=>`${time(x.startAt)}–${time(x.endAt)}`,utc=(d:string,t:string)=>new Date(`${d}T${t}:00+08:00`).toISOString(),days=(start:string)=>Array.from({length:7},(_,i)=>{const d=new Date(`${start}T00:00:00+08:00`);d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10)}),dayLabel=(d:string)=>new Intl.DateTimeFormat("zh-HK",{timeZone:"Asia/Hong_Kong",month:"numeric",day:"numeric",weekday:"short"}).format(new Date(`${d}T00:00:00+08:00`)),fullDay=(d:string)=>new Intl.DateTimeFormat("zh-HK",{timeZone:"Asia/Hong_Kong",month:"long",day:"numeric",weekday:"long"}).format(new Date(`${d}T00:00:00+08:00`));
function hour(iso:string){const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Hong_Kong",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(iso));return +(p.find(x=>x.type==="hour")?.value??0)+ +(p.find(x=>x.type==="minute")?.value??0)/60}
function Timeline({slots,overlaps=[]}:{slots:Interval[];overlaps?:Interval[]}){const mark=(x:Interval,k:string)=>{const s=Math.max(12,hour(x.startAt)),e=Math.min(24,hour(x.endAt)||24);return e<=s||e<=12||s>=24?null:<i key={`${k}${x.startAt}`} className={k} style={{left:`${(s-12)/12*100}%`,width:`${Math.max(1,(e-s)/12*100)}%`}}/>};return <div className="availability-timeline" aria-label="可配對時間線"><div>{slots.map(x=>mark(x,"slot"))}{overlaps.map(x=>mark(x,"overlap"))}</div></div>}
function peak(members:Member[]){const e=members.flatMap(m=>m.slots.flatMap(s=>[{at:Date.parse(s.startAt),n:1},{at:Date.parse(s.endAt),n:-1}])).sort((a,b)=>a.at-b.at);let n=0,i=0,b:{s:number;e:number;n:number}|null=null;while(i<e.length){const at=e[i].at;while(i<e.length&&e[i].at===at)n+=e[i++].n;const next=e[i]?.at;if(next&&n>0&&(!b||n>b.n||(n===b.n&&next-at>b.e-b.s)))b={s:at,e:next,n}}return b?{label:`${time(new Date(b.s).toISOString())}–${time(new Date(b.e).toISOString())}`,count:b.n}:null}
function SlotForm({initialDate,slot,onSave,onCancel}:{initialDate:string;slot?:AvailabilitySlot;onSave:(x:Interval)=>void;onCancel?:()=>void}){
 const[d,setD]=useState(slot?hkDate(new Date(slot.startAt)):initialDate),[s,setS]=useState(slot?time(slot.startAt):"19:00"),[e,setE]=useState(slot?time(slot.endAt):"21:00"),[error,setError]=useState("");
 const times=Array.from({length:48},(_,i)=>`${String(Math.floor(i/2)).padStart(2,"0")}:${i%2?"30":"00"}`);
 const next=e<=s, endDate=new Date(`${d}T00:00:00+08:00`); if(next) endDate.setUTCDate(endDate.getUTCDate()+1);
 const preview=()=>{try{return validateAvailabilityInterval({startAt:new Date(`${d}T${s}:00+08:00`).toISOString(),endAt:new Date(endDate.toISOString().slice(0,10)+`T${e}:00+08:00`).toISOString()})}catch{return null}};
 return <form className="availability-slot-form" onSubmit={ev=>{ev.preventDefault();const x=preview();if(!x)return setError("請選擇未來、至少 30 分鐘且不超過 12 小時的時段。");setError("");onSave(x)}}>
  <label>日期<input type="date" min={hkDate()} value={d} onChange={x=>setD(x.target.value)} required/></label>
  <label>開始時間<select value={s} onChange={x=>setS(x.target.value)}>{times.map(v=><option key={v}>{v}</option>)}</select></label>
  <label>結束時間<select value={e} onChange={x=>setE(x.target.value)}>{times.map(v=><option key={v}>{v}{v<=s?" · 次日":""}</option>)}</select></label>
  <p className="availability-form-preview" aria-live="polite">{preview()?`${dayLabel(d)}，${time(preview()!.startAt)} → ${dayLabel(hkDate(new Date(preview()!.endAt)))} ${time(preview()!.endAt)} · ${Math.round((Date.parse(preview()!.endAt)-Date.parse(preview()!.startAt))/3600000*10)/10} 小時${next?" · 次日結束":""}`:"請完成日期及時間選擇"}</p>
  <small>如果結束時間早於開始時間，時段會在翌日結束。</small><button className="primary">{slot?"儲存變更":"加入時段"}</button>{onCancel&&<button type="button" className="more" onClick={onCancel}>取消</button>}{error&&<p className="availability-form-error" role="alert">{error}</p>}
 </form>
}function PlayerRow({member,mine,isMe}:{member:Member;mine:Interval[];isMe:boolean}){const o=isMe?[]:intersectIntervals(mine,member.slots);return <article className={`availability-player-row${isMe?" is-me":""}`}><div className="availability-player"><PlayerBadge player={member}/><div><b>{member.name}{isMe&&<span>你</span>}</b><small>{Math.round(member.rating)} ELO</small></div></div><div className="availability-row-track"><Timeline slots={member.slots} overlaps={o}/><small>{member.slots.map(range).join("、")}</small></div><strong>{o.length?`${overlapMinutes(o)} 分鐘`:isMe?"你的時段":"未重疊"}</strong></article>}
function Recommendation({item,rank}:{item:Rec;rank:number}){return <article className="recommendation-card"><div className="recommendation-rank">{rank}</div><div className="recommendation-main"><div className="availability-member-head"><PlayerBadge player={item.member}/><div><b>{item.member.name}</b><small>{Math.round(item.member.rating)} ELO</small></div><strong>{item.minutes} 分鐘</strong></div><div className="recommendation-window"><span>共同時段</span><b>{item.overlaps.map(range).join("、")}</b></div><Timeline slots={item.member.slots} overlaps={item.overlaps}/><p>ELO 相差 {Math.round(item.difference)} · 最近 30 日交手 {item.recent} 場</p></div><button className="secondary" disabled>邀請對局 <small>即將推出</small></button></article>}
export default function Availability({userPlayerId,matches}:{userPlayerId?:string;matches:Match[]}){const week=useMemo(()=>days(hkDate()),[]),[date,setDate]=useState(hkDate()),[members,setMembers]=useState<Member[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[own,setOwn]=useState<AvailabilitySlot[]>([]),[view,setView]=useState<View>("find"),[draft,setDraft]=useState<Interval[]>([]),[editing,setEditing]=useState<AvailabilitySlot|null>(null),[pending,setPending]=useState<AvailabilitySlot|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
useEffect(()=>{const c=new AbortController();async function load(){setLoading(true);try{const[selected,all,mine]=await Promise.all([fetch(`/api/availability?date=${date}`,{signal:c.signal}).then(r=>r.json()),Promise.all(week.map(d=>fetch(`/api/availability?date=${d}`,{signal:c.signal}).then(r=>r.json()))),userPlayerId?fetch("/api/availability?me",{signal:c.signal}).then(r=>r.json()):Promise.resolve({slots:[]})]);if(selected.error)throw Error(selected.error);setMembers(selected.members);setOwn(mine.slots??[]);setCounts(Object.fromEntries(week.map((d,i)=>[d,all[i].members?.length??0])));setMessage("")}catch(e){if(e instanceof Error&&e.name!=="AbortError")setMessage(e.message)}finally{if(!c.signal.aborted)setLoading(false)}}trackAvailabilityEvent("availability_date_select");void load();return()=>c.abort()},[date,userPlayerId,week]);useEffect(()=>trackAvailabilityEvent("availability_view"),[]);
const mine=useMemo(()=>clipToDay(own,date),[own,date]),busiest=useMemo(()=>peak(members),[members]),recs=useMemo(()=>{if(!userPlayerId)return[];const me=members.find(x=>x.id===userPlayerId),cut=Date.now()-30*864e5;return members.filter(x=>x.id!==userPlayerId).map(member=>{const overlaps=intersectIntervals(mine,member.slots),minutes=overlapMinutes(overlaps),recent=matches.filter(m=>m.status==="confirmed"&&Date.parse(`${m.playedOn}T00:00:00+08:00`)>=cut&&((m.a===userPlayerId&&m.b===member.id)||(m.b===userPlayerId&&m.a===member.id))).slice(0,5).length,s=recommendationScore({minutes,eloDifference:(me?.rating??0)-member.rating,recentMatches:recent});return s?{member,overlaps,minutes,recent,score:s.score,difference:Math.abs((me?.rating??0)-member.rating)}:null}).filter((x):x is Rec=>Boolean(x)).sort((a,b)=>b.score-a.score||b.minutes-a.minutes||a.difference-b.difference)},[members,matches,mine,userPlayerId]);
const nav=(v:View)=>{if(v==="recommendations")trackAvailabilityEvent("availability_recommendations_view");setView(v)},save=async()=>{const r=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slots:draft})}),b=await r.json();if(!r.ok)return setMessage(b.error);setOwn(b.slots??[]);setDraft([]);setView("manage");setMessage("時段已發佈，推薦已更新。");trackAvailabilityEvent("availability_slot_publish")},update=async(x:Interval)=>{if(!editing)return;const r=await fetch(`/api/availability/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(x)}),b=await r.json();if(!r.ok)return setMessage(b.error);setOwn(a=>a.map(s=>s.id===editing.id?b.slot:s));setEditing(null);setMessage("時段已更新。");trackAvailabilityEvent("availability_slot_edit")},cancel=async()=>{if(!pending)return;const r=await fetch(`/api/availability/${pending.id}`,{method:"DELETE"}),b=await r.json();if(!r.ok)return setMessage(b.error);setOwn(a=>a.filter(x=>x.id!==pending.id));setPending(null);setMessage("時段已取消。");trackAvailabilityEvent("availability_slot_cancel")};
return <section className="availability-page"><section className="hero small availability-hero"><div><p className="kicker">MATCHMAKING</p><h1>找對手，約一局</h1><p>公開你的空閒時間，快速找到最合適的球友。</p></div>{userPlayerId&&<button className="primary" onClick={()=>nav("create")}>＋ 新增時段</button>}</section><nav className="availability-tabs" aria-label="配對功能"><button className={view==="find"?"active":""} onClick={()=>nav("find")}>找對手</button><button className={view==="recommendations"?"active":""} onClick={()=>nav("recommendations")}>推薦{recs.length>0&&<span>{recs.length}</span>}</button>{userPlayerId&&<button className={view==="manage"||view==="create"?"active":""} onClick={()=>nav("manage")}>我的時段</button>}</nav>{(view==="find"||view==="recommendations")&&<div className="date-strip">{week.map((d,i)=><button key={d} className={d===date?"active":""} onClick={()=>setDate(d)}><small>{i?new Intl.DateTimeFormat("zh-HK",{weekday:"short",timeZone:"Asia/Hong_Kong"}).format(new Date(`${d}T00:00:00+08:00`)):"今天"}</small><b>{d.slice(-2)}</b><span>{counts[d]??"–"} 位</span></button>)}</div>}{message&&<p className="availability-notice" role="status">{message}</p>}
{view==="find"&&<div className="availability-layout"><main><header className="availability-day-head"><div><p>{fullDay(date)}</p><h2>{members.length?`${members.length} 位球員有空`:"暫時未有人有空"}</h2></div><button className="more" onClick={()=>nav("recommendations")}>查看推薦 →</button></header>{loading?<div className="availability-skeleton"/>:<>{busiest&&<section className="availability-peak"><span>最多人重疊</span><strong>{busiest.label}</strong><small>{busiest.count} 位球員同時有空</small></section>}<section className="availability-card availability-roster"><div className="timeline-scale"><span>12:00</span><span>15:00</span><span>18:00</span><span>21:00</span><span>00:00</span></div><div className="availability-list">{members.slice().sort((a,b)=>Number(b.id===userPlayerId)-Number(a.id===userPlayerId)).map(m=><PlayerRow key={m.id} member={m} mine={mine} isMe={m.id===userPlayerId}/>)}{!members.length&&<p className="availability-empty">選擇其他日期，或率先公開你的可配對時段。</p>}</div><div className="timeline-legend"><span><i/>球員有空</span><span><i/>與你重疊</span></div></section></>}</main><aside className="availability-sidebar"><section className="availability-card own-availability-card"><small>你的可配對時間</small><h2>{mine.length?mine.map(range).join("、"):"尚未設定"}</h2>{mine.length>0&&<Timeline slots={mine}/>}<p>{mine.length?`${recs.length} 位球員與你重疊至少 30 分鐘`:"加入時段後，我們會按重疊時間及 ELO 推薦對手。"}</p>{userPlayerId?<button className="primary full" onClick={()=>nav(mine.length?"recommendations":"create")}>{mine.length?"查看推薦對手":"新增可配對時段"}</button>:<p className="availability-signin">登入並連結球員帳戶，即可獲得個人推薦。</p>}</section>{recs[0]&&<section className="availability-card best-match"><small>今天最合適</small><div className="availability-member-head"><PlayerBadge player={recs[0].member}/><div><b>{recs[0].member.name}</b><small>{Math.round(recs[0].member.rating)} ELO</small></div></div><strong>{recs[0].minutes} 分鐘重疊</strong><button className="secondary full" onClick={()=>nav("recommendations")}>查看配對詳情</button></section>}</aside></div>}
{view==="recommendations"&&<section className="availability-recommendations"><header className="availability-day-head"><div><p>{fullDay(date)}</p><h2>為你推薦</h2><small>按重疊時間、ELO 差距及近期交手排序</small></div></header>{loading?<div className="availability-skeleton"/>:<div className="availability-list">{recs.map((x,i)=><Recommendation key={x.member.id} item={x} rank={i+1}/>)}{!recs.length&&<section className="availability-card availability-empty-state"><b>{userPlayerId?"這天暫時沒有合適推薦":"登入後查看個人推薦"}</b><p>{userPlayerId?"試試其他日期，或增加你的可配對時段。":"連結球員帳戶後，我們會替你比較共同時段及 ELO。"}</p>{userPlayerId&&<button className="primary" onClick={()=>nav("create")}>新增時段</button>}</section>}</div>}</section>}
{view==="create"&&userPlayerId&&<section className="availability-editor"><header className="availability-day-head"><div><p>步驟 1</p><h2>新增可配對時段</h2><small>可加入不同日期的多個時段，確認後一次發佈。</small></div></header><section className="availability-card"><SlotForm initialDate={date} onSave={x=>setDraft(a=>mergeIntervals([...a,x]))}/></section>{draft.length>0&&<section className="availability-card draft-review"><h2>確認時段（{draft.length}）</h2><div className="slot-list">{draft.map(x=><div key={x.startAt}><span><b>{dayLabel(hkDate(new Date(x.startAt)))}</b>{range(x)}</span><button className="danger-link" onClick={()=>setDraft(a=>a.filter(s=>s.startAt!==x.startAt))}>移除</button></div>)}</div><button className="primary full" onClick={()=>void save()}>發佈 {draft.length} 個時段</button></section>}</section>}
{view==="manage"&&userPlayerId&&<section className="availability-editor"><header className="availability-day-head"><div><p>管理可配對時間</p><h2>我的未來時段</h2><small>已過期的時段會自動隱藏。</small></div><button className="primary" onClick={()=>nav("create")}>＋ 新增</button></header>{editing?<section className="availability-card"><SlotForm initialDate={hkDate(new Date(editing.startAt))} slot={editing} onSave={update} onCancel={()=>setEditing(null)}/></section>:<div className="availability-list manage-slot-list">{own.map(x=><article className="availability-card" key={x.id}><div><small>{dayLabel(hkDate(new Date(x.startAt)))}</small><b>{range(x)}</b></div><Timeline slots={[x]}/><div><button className="more" onClick={()=>setEditing(x)}>編輯</button><button className="danger-link" onClick={()=>setPending(x)}>取消</button></div></article>)}{!own.length&&<section className="availability-card availability-empty-state"><b>尚未有未來時段</b><p>公開空閒時間後，其他球員就能找到你。</p><button className="primary" onClick={()=>nav("create")}>新增第一個時段</button></section>}</div>}</section>}
{pending&&<div className="availability-dialog-backdrop" onMouseDown={()=>setPending(null)}><section className="availability-dialog" role="alertdialog" aria-modal="true" aria-labelledby="cancel-title" onMouseDown={e=>e.stopPropagation()}><small>取消可配對時段</small><h2 id="cancel-title">{dayLabel(hkDate(new Date(pending.startAt)))} {range(pending)}</h2><p>取消後，這段時間不會再出現在其他球員的配對結果中。</p><div><button className="more" onClick={()=>setPending(null)}>保留時段</button><button className="danger" onClick={()=>void cancel()}>確認取消</button></div></section></div>}</section>}