"use client";

import { useEffect, useMemo, useState } from "react";
import { PlayerBadge } from "./UiBits";
import { trackAvailabilityEvent } from "../lib/availability-analytics";
import { clipToDay, intersectIntervals, mergeIntervals, overlapMinutes, recommendationScore, type AvailabilitySlot, type Interval } from "../lib/availability";

type Player={id:string;name:string;short:string;rating:number;colour?:string;avatar?:string|null};
type Match={a:string;b:string;playedOn:string;status:"confirmed"|"void"};
type Member=Player&{slots:AvailabilitySlot[]};
type View="home"|"members"|"recommendations"|"manage"|"create";
const hkDate=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Hong_Kong",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const time=(iso:string)=>new Intl.DateTimeFormat("zh-HK",{timeZone:"Asia/Hong_Kong",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso));
const range=(slot:Interval)=>`${time(slot.startAt)}–${time(slot.endAt)}`;
const utc=(date:string,value:string)=>new Date(`${date}T${value}:00+08:00`).toISOString();
const days=(start:string)=>Array.from({length:7},(_,i)=>{const d=new Date(`${start}T00:00:00+08:00`);d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);});

function Timeline({slots,overlaps=[]}:{slots:Interval[];overlaps?:Interval[]}){const value=(iso:string)=>{const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Hong_Kong",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(iso));return +(p.find(x=>x.type==="hour")?.value??0)+(+(p.find(x=>x.type==="minute")?.value??0))/60};const mark=(slot:Interval,kind:string)=><i key={`${kind}${slot.startAt}`} className={kind} style={{left:`${value(slot.startAt)/24*100}%`,width:`${Math.max(1,(value(slot.endAt)-value(slot.startAt))/24*100)}%`}}/>;return <div className="availability-timeline"><small>00</small><div>{slots.map(x=>mark(x,"slot"))}{overlaps.map(x=>mark(x,"overlap"))}</div><small>24</small></div>}
function SlotForm({date,slot,onSave,onCancel}:{date:string;slot?:AvailabilitySlot;onSave:(x:Interval)=>void;onCancel?:()=>void}){const [start,setStart]=useState(slot?time(slot.startAt):"19:00"),[end,setEnd]=useState(slot?time(slot.endAt):"21:00");return <form className="availability-slot-form" onSubmit={e=>{e.preventDefault();const item={startAt:utc(date,start),endAt:utc(date,end)};if(item.endAt<=item.startAt)return alert("結束時間必須晚於開始時間。");onSave(item)}}><label>開始<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>結束<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required/></label><button className="primary">{slot?"儲存":"加入時段"}</button>{onCancel&&<button className="more" type="button" onClick={onCancel}>取消</button>}</form>}
function Card({member,overlaps=[]}:{member:Member;overlaps?:Interval[]}){return <article className="availability-member"><div className="availability-member-head"><PlayerBadge player={member}/><div><b>{member.name}</b><small>{Math.round(member.rating)} ELO</small></div>{overlaps.length>0&&<strong>{overlapMinutes(overlaps)} 分鐘</strong>}</div><p>{member.slots.map(range).join("、")}</p><Timeline slots={member.slots} overlaps={overlaps}/></article>}

export default function Availability({userPlayerId,matches}:{userPlayerId?:string;matches:Match[]}){
  const [date,setDate]=useState(hkDate()),[members,setMembers]=useState<Member[]>([]),[own,setOwn]=useState<AvailabilitySlot[]>([]),[view,setView]=useState<View>("home"),[draft,setDraft]=useState<Interval[]>([]),[editing,setEditing]=useState<AvailabilitySlot|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const load=async()=>{setLoading(true);try{const day=await fetch(`/api/availability?date=${date}`).then(r=>r.json());if(day.error)throw Error(day.error);setMembers(day.members);if(userPlayerId){const mine=await fetch("/api/availability?me").then(r=>r.json());setOwn(mine.slots??[]);}}catch(e){setMessage(e instanceof Error?e.message:"未能載入時段")}finally{setLoading(false)}};
  useEffect(()=>{trackAvailabilityEvent("availability_date_select");void load()},[date,userPlayerId]);
  useEffect(()=>{trackAvailabilityEvent("availability_view")},[]);
  const mine=useMemo(()=>clipToDay(own,date),[own,date]);
  const recommendations=useMemo(()=>{if(!userPlayerId)return [];const me=members.find(x=>x.id===userPlayerId);const cutoff=Date.now()-30*864e5;return members.filter(x=>x.id!==userPlayerId).map(member=>{const overlaps=intersectIntervals(mine,member.slots),minutes=overlapMinutes(overlaps),recent=matches.filter(m=>m.status==="confirmed"&&Date.parse(`${m.playedOn}T00:00:00+08:00`)>=cutoff&&((m.a===userPlayerId&&m.b===member.id)||(m.b===userPlayerId&&m.a===member.id))).slice(0,5).length;const scoring=recommendationScore({minutes,eloDifference:(me?.rating??0)-member.rating,recentMatches:recent});return scoring?{member,overlaps,minutes,recent,score:scoring.score,difference:Math.abs((me?.rating??0)-member.rating)}:null}).filter(Boolean).sort((a,b)=>b!.score-a!.score||b!.minutes-a!.minutes||a!.difference-b!.difference) as {member:Member;overlaps:Interval[];minutes:number;recent:number;score:number;difference:number}[]},[members,matches,mine,userPlayerId]);
  const save=async()=>{const response=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slots:draft})});const body=await response.json();if(!response.ok)return setMessage(body.error);setDraft([]);setView("manage");setMessage("時段已發佈，推薦已更新。");trackAvailabilityEvent("availability_slot_publish");void load()};
  const update=async(item:Interval)=>{if(!editing)return;const r=await fetch(`/api/availability/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(item)});if(!r.ok)return setMessage((await r.json()).error);setEditing(null);setMessage("時段已更新。");trackAvailabilityEvent("availability_slot_edit");void load()};
  const cancel=async(id:string)=>{if(!confirm("確定取消這個可配對時段？"))return;const r=await fetch(`/api/availability/${id}`,{method:"DELETE"});if(!r.ok)return setMessage((await r.json()).error);setMessage("時段已取消。");trackAvailabilityEvent("availability_slot_cancel");void load()};
  const nav=(id:View,label:string)=><button className={view===id?"active":""} onClick={()=>{if(id==="recommendations")trackAvailabilityEvent("availability_recommendations_view");setView(id)}}>{label}</button>;
  if(loading)return <section className="availability-page"><section className="hero small"><div><p className="kicker">MATCHMAKING</p><h1>可配對時段</h1></div></section><div className="availability-skeleton"/></section>;
  return <section className="availability-page"><section className="hero small"><div><p className="kicker">MATCHMAKING</p><h1>可配對時段</h1><p>香港時間 · 公開查看 · 以重疊時間推薦對手</p></div>{userPlayerId&&<button className="primary" onClick={()=>setView("create")}>＋ 新增時段</button>}</section><div className="availability-tabs">{nav("home","總覽")}{nav("members","會員")}{nav("recommendations","推薦")}{userPlayerId&&nav("manage","我的時段")}</div><div className="date-strip">{days(hkDate()).map(day=><button key={day} className={day===date?"active":""} onClick={()=>setDate(day)}><small>{new Intl.DateTimeFormat("zh-HK",{weekday:"short",timeZone:"Asia/Hong_Kong"}).format(new Date(`${day}T00:00:00+08:00`))}</small><b>{day.slice(-2)}</b></button>)}</div>{message&&<p className="availability-notice" role="status">{message}</p>}
    {view==="home"&&<><div className="availability-summary"><div><small>當日會員</small><b>{members.length}</b><span>位有空</span></div><div><small>我的時段</small><b>{mine.length}</b><span>個可配對區間</span></div><div><small>推薦對手</small><b>{recommendations.length}</b><span>重疊至少 30 分鐘</span></div></div><section className="availability-card"><div className="section-title"><h2>當日會員</h2><button className="more" onClick={()=>setView("members")}>查看全部</button></div>{members.length?members.slice(0,3).map(m=><Card key={m.id} member={m} overlaps={m.id===userPlayerId?[]:intersectIntervals(mine,m.slots)}/>):<p className="availability-empty">這天暫時沒有人有空。</p>}</section><section className="availability-card"><div className="section-title"><h2>推薦對手</h2><button className="more" onClick={()=>setView("recommendations")}>完整排名</button></div>{recommendations.slice(0,3).map(x=><Card key={x.member.id} member={x.member} overlaps={x.overlaps}/>)}{!recommendations.length&&<p className="availability-empty">{userPlayerId?"建立時段後會顯示至少重疊 30 分鐘的對手。":"登入並連結球員帳戶後可查看個人推薦。"}</p>}</section></>}
    {view==="members"&&<div className="availability-list">{members.map(m=><Card key={m.id} member={m} overlaps={m.id===userPlayerId?[]:intersectIntervals(mine,m.slots)}/>)}</div>}
    {view==="recommendations"&&<div className="availability-list">{recommendations.map((x,i)=><article className="recommendation-card" key={x.member.id}><b>#{i+1}</b><div><Card member={x.member} overlaps={x.overlaps}/><p>重疊 {x.minutes} 分鐘 · ELO 相差 {Math.round(x.difference)} · 最近 30 日交手 {x.recent} 場</p></div><strong>{x.score}</strong></article>)}{!recommendations.length&&<p className="availability-empty">沒有符合最少 30 分鐘重疊的推薦。</p>}</div>}
    {view==="create"&&userPlayerId&&<section className="availability-card"><h2>新增時段</h2><SlotForm date={date} onSave={slot=>setDraft(d=>mergeIntervals([...d,slot]))}/>{draft.length>0&&<><div className="slot-list">{draft.map(slot=><div key={slot.startAt}><span>{range(slot)}</span><button className="more" onClick={()=>setDraft(d=>d.filter(x=>x.startAt!==slot.startAt))}>移除</button></div>)}</div><button className="primary full" onClick={()=>void save()}>發佈 {draft.length} 個時段</button></>}</section>}
    {view==="manage"&&userPlayerId&&<section className="availability-card"><div className="section-title"><h2>我的未來時段</h2><button className="more" onClick={()=>setView("create")}>新增</button></div>{editing?<SlotForm date={hkDate(new Date(editing.startAt))} slot={editing} onSave={update} onCancel={()=>setEditing(null)}/>:<div className="slot-list">{own.map(slot=><div key={slot.id}><span>{new Intl.DateTimeFormat("zh-HK",{timeZone:"Asia/Hong_Kong",month:"numeric",day:"numeric",weekday:"short"}).format(new Date(slot.startAt))} {range(slot)}</span><span><button className="more" onClick={()=>setEditing(slot)}>編輯</button><button className="danger-link" onClick={()=>void cancel(slot.id)}>取消</button></span></div>)}{!own.length&&<p className="availability-empty">尚未有未來時段。</p>}</div>}</section>}
  </section>;
}
