"use client";
import {useEffect,useRef,type ReactNode} from "react";
export function Dialog({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const before=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>("button,input,select,textarea,a")?.focus();const key=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);before?.focus()}},[open,onClose]);if(!open)return null;return <div className="ds-overlay" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div ref={ref} className="ds-dialog" role="dialog" aria-modal="true" aria-labelledby="ds-dialog-title"><button className="ds-dialog-close" onClick={onClose} aria-label="關閉">×</button><h2 id="ds-dialog-title">{title}</h2>{children}</div></div>}
export function Sheet({open,title,children,onClose,className=""}:{open:boolean;title:string;children:ReactNode;onClose:()=>void;className?:string}){if(!open)return null;return <div className="ds-overlay ds-overlay--sheet" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className={`ds-sheet${className?` ${className}`:""}`} role="dialog" aria-modal="true" aria-labelledby="ds-sheet-title"><button className="ds-dialog-close" onClick={onClose} aria-label="關閉">×</button><h2 id="ds-sheet-title">{title}</h2>{children}</section></div>}
/** Shared scaffold for the app's pre-existing `.backdrop`/`.sheet.invite-sheet` bottom-sheet pattern
    (invite composers, session/slot creation, counter-offers). Kept on the legacy classes rather than
    `.ds-sheet` since those carry their own established styling — this only removes the identical
    backdrop/close-button/aria wiring that was duplicated across each call site. */
export function BackdropSheet({onClose,labelledBy,className,children}:{onClose:()=>void;labelledBy?:string;className?:string;children:ReactNode}){return <div className="backdrop invite-backdrop" onMouseDown={onClose}><section className={`sheet invite-sheet${className?` ${className}`:""}`} onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby={labelledBy}><button type="button" className="close" aria-label="關閉" onClick={onClose}>×</button>{children}</section></div>}
