"use client";
import {useLayoutEffect,useRef,useState} from "react";
import type {ButtonHTMLAttributes,CSSProperties,HTMLAttributes,ReactNode} from "react";
type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"featured"|"secondary"|"quiet"|"danger";loading?:boolean};
export function Button({variant="primary",loading=false,disabled,className="",children,...props}:ButtonProps){return <button {...props} disabled={disabled||loading} aria-busy={loading||undefined} className={`ds-button ds-button--${variant} ${className}`.trim()}>{loading&&<span className="ds-spinner" aria-hidden="true"/>}<span>{loading?"處理中…":children}</span></button>}
export function IconButton({label,className="",children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string;children:ReactNode}){return <button {...props} aria-label={label} className={`ds-icon-button ${className}`.trim()}>{children}</button>}
export function Surface({tone="primary",as:Tag="section",padded=true,className="",...props}:HTMLAttributes<HTMLElement>&{tone?:"primary"|"raised"|"featured";as?:"section"|"article"|"li"|"div"|"button";padded?:boolean}){return <Tag {...props} className={`ds-surface ds-surface--${tone}${padded?"":" ds-surface--unpadded"} ${className}`.trim()}/>}
export function SegmentedControl({label,value,items,onChange}:{label:string;value:string;items:{value:string;label:string}[];onChange:(value:string)=>void}){const activeIndex=Math.max(0,items.findIndex(item=>item.value===value));const gap=4;const motionStyle={"--segment-width":`calc((100% - ${(items.length+1)*gap}px) / ${items.length})`,"--segment-translate":`calc(${activeIndex*100}% + ${activeIndex*gap}px)`} as CSSProperties;return <div className="ds-segmented" role="tablist" aria-label={label} style={motionStyle}><i className="ds-segmented__indicator" aria-hidden="true"/>{items.map(item=><button key={item.value} type="button" role="tab" aria-selected={value===item.value} onClick={()=>onChange(item.value)}><span>{item.label}</span></button>)}</div>}
export function SlidingToggleGroup({as:Tag="div",className="",children,style,...props}:HTMLAttributes<HTMLElement>&{as?:"div"|"nav"}){const ref=useRef<HTMLElement|null>(null);const [thumb,setThumb]=useState({x:0,y:0,width:0,height:0});useLayoutEffect(()=>{const group=ref.current;if(!group)return;const measure=()=>{const active=group.querySelector<HTMLElement>('button.active,button[aria-selected="true"],button[aria-pressed="true"]');if(active)setThumb({x:active.offsetLeft,y:active.offsetTop,width:active.offsetWidth,height:active.offsetHeight})};measure();const observer=new ResizeObserver(measure);observer.observe(group);return()=>observer.disconnect()},[children]);const motionStyle={...style,"--toggle-x":`${thumb.x}px`,"--toggle-y":`${thumb.y}px`,"--toggle-width":`${thumb.width}px`,"--toggle-height":`${thumb.height}px`} as CSSProperties;return <Tag {...props} ref={node=>{ref.current=node}} className={`sliding-toggle-group ${className}`.trim()} style={motionStyle}><i className="sliding-toggle-thumb" aria-hidden="true"/>{children}</Tag>}
export function FormField({label,hint,error,children}:{label:string;hint?:string;error?:string;children:ReactNode}){return <label className={`ds-field${error?" ds-field--error":""}`}><span>{label}</span>{children}{(error||hint)&&<small>{error||hint}</small>}</label>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="ds-empty"><span aria-hidden="true">◇</span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function InlineNotice({tone="info",title,children}:{tone?:"info"|"success"|"warning"|"danger";title:string;children:ReactNode}){return <div className={`ds-notice ds-notice--${tone}`} role={tone==="danger"?"alert":"status"}><b>{title}</b><span>{children}</span></div>}
export function Skeleton({width="100%",height="1rem",className=""}:{width?:string;height?:string;className?:string}){return <span className={`ds-skeleton ${className}`.trim()} aria-hidden="true" style={{width,height}}/>}
export function StatTile({label,value,className=""}:{label:ReactNode;value:ReactNode;className?:string}){return <div className={`ds-stat-tile ${className}`.trim()}><small>{label}</small><b>{value}</b></div>}
export function ChipRow({items,className=""}:{items:string[];className?:string}){if(!items.length)return null;return <div className={`ds-chip-row ${className}`.trim()}>{items.map(item=><span key={item} className="ds-chip">{item}</span>)}</div>}
export function Chip({tone="neutral",className="",children,...props}:HTMLAttributes<HTMLSpanElement>&{tone?:"neutral"|"accent"|"success"|"warning"|"danger"}){return <span {...props} className={`ds-chip ds-chip--${tone} ${className}`.trim()}>{children}</span>}
