"use client";
import type {ButtonHTMLAttributes,HTMLAttributes,ReactNode} from "react";
type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"featured"|"secondary"|"quiet"|"danger";loading?:boolean};
export function Button({variant="primary",loading=false,disabled,className="",children,...props}:ButtonProps){return <button {...props} disabled={disabled||loading} aria-busy={loading||undefined} className={`ds-button ds-button--${variant} ${className}`.trim()}>{loading&&<span className="ds-spinner" aria-hidden="true"/>}<span>{loading?"處理中…":children}</span></button>}
export function IconButton({label,className="",children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string;children:ReactNode}){return <button {...props} aria-label={label} className={`ds-icon-button ${className}`.trim()}>{children}</button>}
export function Surface({tone="primary",as:Tag="section",padded=true,className="",...props}:HTMLAttributes<HTMLElement>&{tone?:"primary"|"raised"|"featured";as?:"section"|"article"|"li"|"div"|"button";padded?:boolean}){return <Tag {...props} className={`ds-surface ds-surface--${tone}${padded?"":" ds-surface--unpadded"} ${className}`.trim()}/>}
export function SegmentedControl({label,value,items,onChange}:{label:string;value:string;items:{value:string;label:string}[];onChange:(value:string)=>void}){return <div className="ds-segmented" role="tablist" aria-label={label}>{items.map(item=><button key={item.value} type="button" role="tab" aria-selected={value===item.value} onClick={()=>onChange(item.value)}>{item.label}</button>)}</div>}
export function FormField({label,hint,error,children}:{label:string;hint?:string;error?:string;children:ReactNode}){return <label className={`ds-field${error?" ds-field--error":""}`}><span>{label}</span>{children}{(error||hint)&&<small>{error||hint}</small>}</label>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="ds-empty"><span aria-hidden="true">◇</span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function InlineNotice({tone="info",title,children}:{tone?:"info"|"success"|"warning"|"danger";title:string;children:ReactNode}){return <div className={`ds-notice ds-notice--${tone}`} role={tone==="danger"?"alert":"status"}><b>{title}</b><span>{children}</span></div>}
export function Skeleton({width="100%",height="1rem",className=""}:{width?:string;height?:string;className?:string}){return <span className={`ds-skeleton ${className}`.trim()} aria-hidden="true" style={{width,height}}/>}
export function StatTile({label,value,className=""}:{label:ReactNode;value:ReactNode;className?:string}){return <div className={`ds-stat-tile ${className}`.trim()}><small>{label}</small><b>{value}</b></div>}
export function ChipRow({items,className=""}:{items:string[];className?:string}){if(!items.length)return null;return <div className={`ds-chip-row ${className}`.trim()}>{items.map(item=><span key={item} className="ds-chip">{item}</span>)}</div>}
export function Chip({tone="neutral",className="",children,...props}:HTMLAttributes<HTMLSpanElement>&{tone?:"neutral"|"accent"|"success"|"warning"|"danger"}){return <span {...props} className={`ds-chip ds-chip--${tone} ${className}`.trim()}>{children}</span>}
