ALTER TABLE state_players ADD COLUMN IF NOT EXISTS short text;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS handicap numeric;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS colour text;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS initial_rating numeric;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS wins integer NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS losses integer NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS draws integer NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS frames_won integer NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS frames_lost integer NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS last_change numeric NOT NULL DEFAULT 0;
ALTER TABLE state_players ADD COLUMN IF NOT EXISTS form jsonb NOT NULL DEFAULT '[]'::jsonb;
UPDATE state_players SET short=COALESCE(short,payload->>'short',left(name,3)), handicap=COALESCE(handicap,(payload->>'handicap')::numeric), colour=COALESCE(colour,payload->>'colour'), initial_rating=COALESCE(initial_rating,(payload->>'initialRating')::numeric,rating), wins=COALESCE((payload->>'wins')::integer,0), losses=COALESCE((payload->>'losses')::integer,0), draws=COALESCE((payload->>'draws')::integer,0), frames_won=COALESCE((payload->>'framesWon')::integer,0), frames_lost=COALESCE((payload->>'framesLost')::integer,0), last_change=COALESCE((payload->>'lastChange')::numeric,0), form=COALESCE(payload->'form','[]'::jsonb);
ALTER TABLE state_players ALTER COLUMN short SET NOT NULL;
ALTER TABLE state_players ALTER COLUMN initial_rating SET NOT NULL;
ALTER TABLE state_players DROP COLUMN IF EXISTS payload;

ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS score_a integer;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS score_b integer;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS entry_mode text;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS frame_evidence numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS performance_score numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS evidence_weight numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS handicap_adjustment numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS over_handicap_elo numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS over_handicap_multiplier numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS high_breaks jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS player_a2 text;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS player_b2 text;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS mode text;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS actual numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS giver text;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS official numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS extra numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS expected_a numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS before_a numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS before_b numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS before_a2 numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS before_b2 numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS after_a numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS after_b numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS after_a2 numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS after_b2 numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS delta_a numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS margin_multiplier numeric;
ALTER TABLE state_matches ADD COLUMN IF NOT EXISTS created_at timestamptz;
UPDATE state_matches SET score_a=(payload->>'scoreA')::integer,score_b=(payload->>'scoreB')::integer,entry_mode=payload->>'entryMode',frame_evidence=(payload->>'frameEvidence')::numeric,performance_score=(payload->>'performanceScore')::numeric,evidence_weight=(payload->>'evidenceWeight')::numeric,handicap_adjustment=(payload->>'handicapAdjustment')::numeric,over_handicap_elo=(payload->>'overHandicapElo')::numeric,over_handicap_multiplier=(payload->>'overHandicapMultiplier')::numeric,high_breaks=COALESCE(payload->'highBreaks','[]'::jsonb),actual=(payload->>'actual')::numeric,giver=payload->>'giver',official=(payload->>'official')::numeric,extra=(payload->>'extra')::numeric,expected_a=(payload->>'expectedA')::numeric,before_a=(payload->>'beforeA')::numeric,before_b=(payload->>'beforeB')::numeric,before_a2=(payload->>'beforeA2')::numeric,before_b2=(payload->>'beforeB2')::numeric,after_a=(payload->>'afterA')::numeric,after_b=(payload->>'afterB')::numeric,after_a2=(payload->>'afterA2')::numeric,after_b2=(payload->>'afterB2')::numeric,delta_a=(payload->>'deltaA')::numeric,margin_multiplier=(payload->>'marginMultiplier')::numeric,created_at=COALESCE((payload->>'createdAt')::timestamptz,updated_at);
ALTER TABLE state_matches ALTER COLUMN score_a SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN score_b SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN actual SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN extra SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN expected_a SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN before_a SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN before_b SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN after_a SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN after_b SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN delta_a SET NOT NULL;
ALTER TABLE state_matches ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE state_matches DROP COLUMN IF EXISTS payload;

CREATE TABLE IF NOT EXISTS state_settings (id boolean PRIMARY KEY DEFAULT true CHECK (id), data jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO state_settings (id,data,updated_at) SELECT true,data->'settings',updated_at FROM app_state WHERE id=1 ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS state_audits (id text PRIMARY KEY,text text NOT NULL,occurred_at timestamptz NOT NULL);
INSERT INTO state_audits (id,text,occurred_at) SELECT audit->>'id',audit->>'text',(audit->>'at')::timestamptz FROM app_state,jsonb_array_elements(COALESCE(data->'audits','[]'::jsonb)) audit ON CONFLICT (id) DO NOTHING;
ALTER TABLE state_matches ADD CONSTRAINT state_matches_player_a_fkey FOREIGN KEY (player_a) REFERENCES state_players(id) ON DELETE RESTRICT;
ALTER TABLE state_matches ADD CONSTRAINT state_matches_player_b_fkey FOREIGN KEY (player_b) REFERENCES state_players(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS state_audits_occurred_at_idx ON state_audits (occurred_at DESC);
